#############################################
#           FPML Make Include File          #
#############################################
# Update any of the following variables as
# you see fit. The compiler and flag variables
# will affect make install and make compile
# and the test variables will affect make run.
#############################################

# fortran compiler and flags
FC := gfortran
FFLAGS := -O2

# latex compiler and flags
LC := pdflatex
LFLAGS :=